### ISSUE TITLE
Your blog post 👍🏽 

### ISSUE THREAD

**Issue by pat-alt** [sdobber/sdobber.github.io#2]
Hi @sdobber 👋🏽  not an issue ... just to let you know that I've found your [blog post](https://sdobber.github.io/juliapackage/) on Julia packages very helpful 🙏🏽 I first came across it about a year ago when I just got started with Julia and have come back to it time and again for a quick reference. Have mentioned it in a tweet [here](https://sdobber.github.io/juliapackage/) (couldn't find you on Twitter though, otherwise I would have just tagged you there).

**Comment by sdobber** [comment]
Hi @pat-alt! Thank you for the nice feedback! I'm glad you liked the post! It took me quite a while to put all the pieces together when I started registering my first package, so I thought that it might be a good idea to write that down somehow - good to hear that other people find it useful too!
